/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author chelunike
 */
public class VentanaPatidos extends javax.swing.JDialog {

    /**
     * Creates new form VentanaPatidos
     */
    public VentanaPatidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComBoxEquipo1 = new javax.swing.JComboBox<>();
        jComBoxEquipo2 = new javax.swing.JComboBox<>();
        jLabelVS = new javax.swing.JLabel();
        jLabelGoles1 = new javax.swing.JLabel();
        jLabelGoles2 = new javax.swing.JLabel();
        jButtonGoles1Add = new javax.swing.JButton();
        jButtonGoles1Remove = new javax.swing.JButton();
        jButtonGoles2Remove = new javax.swing.JButton();
        jButtonGoles2Add = new javax.swing.JButton();
        jScrollPaneEquipo1 = new javax.swing.JScrollPane();
        jPanelEquipo1 = new javax.swing.JPanel();
        jScrollPaneEquipo2 = new javax.swing.JScrollPane();
        jPanelEquipo2 = new javax.swing.JPanel();
        jLabelTarj1 = new javax.swing.JLabel();
        jLabelTarj2 = new javax.swing.JLabel();
        jScrollPaneTarj1 = new javax.swing.JScrollPane();
        jPanelTarj1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanelTarj2 = new javax.swing.JPanel();
        jButtonTarj1Add = new javax.swing.JButton();
        jButtonTarj1Remove = new javax.swing.JButton();
        jButtonTarj2Add = new javax.swing.JButton();
        jButtonTarj2Remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(201, 31, 167));
        setMinimumSize(new java.awt.Dimension(210, 290));

        jLabelVS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVS.setText("vs");

        jLabelGoles1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGoles1.setText("Goles");

        jLabelGoles2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGoles2.setText("Goles");

        jButtonGoles1Add.setText("+");

        jButtonGoles1Remove.setText("-");

        jButtonGoles2Remove.setText("-");

        jButtonGoles2Add.setText("+");

        jScrollPaneEquipo1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelEquipo1.setBackground(new java.awt.Color(254, 254, 254));
        jPanelEquipo1.setLayout(new java.awt.GridBagLayout());
        jScrollPaneEquipo1.setViewportView(jPanelEquipo1);

        jScrollPaneEquipo2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneEquipo2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanelEquipo2.setBackground(new java.awt.Color(254, 254, 254));
        jPanelEquipo2.setLayout(new java.awt.GridBagLayout());
        jScrollPaneEquipo2.setViewportView(jPanelEquipo2);

        jLabelTarj1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTarj1.setText("Tarjetas");

        jLabelTarj2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTarj2.setText("Tarjetas");

        jScrollPaneTarj1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelTarj1.setBackground(new java.awt.Color(254, 254, 254));
        jPanelTarj1.setLayout(new java.awt.GridBagLayout());
        jScrollPaneTarj1.setViewportView(jPanelTarj1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelTarj2.setBackground(new java.awt.Color(254, 254, 254));
        jPanelTarj2.setLayout(new java.awt.GridBagLayout());
        jScrollPane2.setViewportView(jPanelTarj2);

        jButtonTarj1Add.setText("+");

        jButtonTarj1Remove.setText("-");

        jButtonTarj2Add.setText("+");

        jButtonTarj2Remove.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTarj1)
                    .addComponent(jLabelTarj1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGoles1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComBoxEquipo1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneEquipo1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTarj1Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTarj1Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGoles1Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGoles1Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addComponent(jLabelVS, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPaneEquipo2)
                    .addComponent(jLabelGoles2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComBoxEquipo2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarj2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGoles2Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGoles2Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTarj2Add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTarj2Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 188, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComBoxEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComBoxEquipo2)
                    .addComponent(jLabelVS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelGoles1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelGoles2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEquipo2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jScrollPaneEquipo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGoles1Add)
                    .addComponent(jButtonGoles1Remove)
                    .addComponent(jButtonGoles2Add)
                    .addComponent(jButtonGoles2Remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarj1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTarj2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTarj1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTarj1Add)
                    .addComponent(jButtonTarj1Remove)
                    .addComponent(jButtonTarj2Add)
                    .addComponent(jButtonTarj2Remove))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPatidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPatidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPatidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPatidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPatidos dialog = new VentanaPatidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGoles1Add;
    private javax.swing.JButton jButtonGoles1Remove;
    private javax.swing.JButton jButtonGoles2Add;
    private javax.swing.JButton jButtonGoles2Remove;
    private javax.swing.JButton jButtonTarj1Add;
    private javax.swing.JButton jButtonTarj1Remove;
    private javax.swing.JButton jButtonTarj2Add;
    private javax.swing.JButton jButtonTarj2Remove;
    private javax.swing.JComboBox<String> jComBoxEquipo1;
    private javax.swing.JComboBox<String> jComBoxEquipo2;
    private javax.swing.JLabel jLabelGoles1;
    private javax.swing.JLabel jLabelGoles2;
    private javax.swing.JLabel jLabelTarj1;
    private javax.swing.JLabel jLabelTarj2;
    private javax.swing.JLabel jLabelVS;
    private javax.swing.JPanel jPanelEquipo1;
    private javax.swing.JPanel jPanelEquipo2;
    private javax.swing.JPanel jPanelTarj1;
    private javax.swing.JPanel jPanelTarj2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneEquipo1;
    private javax.swing.JScrollPane jScrollPaneEquipo2;
    private javax.swing.JScrollPane jScrollPaneTarj1;
    // End of variables declaration//GEN-END:variables
}
